name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  # Always check packaging
  check-packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install build dependencies
      run: pip install build twine
    - name: Build
      run: python -m build .
    - name: Check build
      run: python -m twine check dist/*
  # Publish only on tags
  build-and-publish:
    needs: check-packaging
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/example-package-daemo/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install build dependencies
      run: pip install build
    - name: Build
      run: python -m build .
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
