name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_run:
    workflows: [ Check packaging ]
    types: [ completed ]

jobs:
  build-and-publish:
    if: >-
      github.ref_type == 'tag' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/example-package-daemo/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install build dependencies
      run: pip install build
    - name: Build
      run: python -m build .
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
